repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: \.svg$
      - id: end-of-file-fixer
        exclude: \.svg$
      - id: check-yaml
      - id: check-added-large-files
        exclude: web/public/hu_preflop_cache\.bin

  - repo: local
    hooks:
      - id: cargo-fmt
        language: system
        name: cargo fmt
        entry: cargo fmt --all -- --check
        types:
          - rust
